import type { Metadata } from 'next';
import LegalPage from '@/components/ui/LegalPage';

export const metadata: Metadata = { title: 'Terms of Service' };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="August 2026">
      <p>
        By creating an account or using the Retinexus AI portal, you agree to the terms below.
      </p>

      <section>
        <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>What this is</h2>
        <p className="mt-2">
          Retinexus AI is a final year project — a working demonstration of an AI-assisted diabetic retinopathy
          and multi-organ risk screening pipeline. It is <strong>not</strong> a certified medical device and has
          not been clinically validated for real-world diagnostic use.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>Not a substitute for a doctor</h2>
        <p className="mt-2">
          Every report generated by this system is AI-assisted and must be reviewed and approved by a qualified
          doctor before it carries any clinical weight. Nothing produced by this portal should be treated as a
          final diagnosis on its own.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>Account responsibility</h2>
        <p className="mt-2">
          Doctors are responsible for the accuracy of the patient records they enter and for keeping their login
          credentials secure. Access to a patient&apos;s data should be limited to those with a legitimate reason
          to view it.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>No warranty</h2>
        <p className="mt-2">
          The service is provided as-is, as an academic prototype. We make no guarantee of uptime, accuracy, or
          fitness for any particular clinical purpose.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>Contact</h2>
        <p className="mt-2">
          Questions about these terms can be directed to the project team at COMSATS University Islamabad,
          Lahore Campus.
        </p>
      </section>
    </LegalPage>
  );
}
