import type { Metadata } from 'next';
import Nav from '@/components/Nav';
import PageHero from '@/components/ui/PageHero';
import LegalContent from '@/components/ui/LegalContent';
import Footer from '@/components/Footer';

export const metadata: Metadata = { title: 'Terms of Service | Retinexus AI' };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--background)] overflow-x-hidden">
      <Nav />
      <PageHero
        eyebrow="Legal"
        title="Terms of Service"
        description="What Retinexus AI is, and what it isn't."
      />
      <LegalContent updated="August 2026">
        <section>
          <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>What this is</h2>
          <p className="mt-2">
            Retinexus AI is a final year project: a working demonstration of an AI-assisted diabetic
            retinopathy and multi-organ risk screening pipeline. It is <strong>not</strong> a certified medical
            device and has not been clinically validated for real-world diagnostic use.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>Not a substitute for a doctor</h2>
          <p className="mt-2">
            Every report generated by the clinical portal is AI-assisted and must be reviewed and approved by a
            qualified doctor before it carries any clinical weight. Nothing produced by this system should be
            treated as a final diagnosis on its own.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>No warranty</h2>
          <p className="mt-2">
            The site and portal are provided as-is, as an academic prototype, with no guarantee of uptime,
            accuracy, or fitness for any particular clinical purpose.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold" style={{ color: 'var(--foreground)' }}>Contact</h2>
          <p className="mt-2">
            Questions about these terms can be directed to the project team at COMSATS University Islamabad,
            Lahore Campus.
          </p>
        </section>
      </LegalContent>
      <Footer />
    </div>
  );
}
