# src/llm_report/prompt_templates.py

CLINICAL_SYSTEM_PROMPT = """
You are an expert retinal specialist and clinical AI assistant. Your task is to interpret multi-modal deep learning diagnostics and convert raw JSON data into a highly professional, structured, and empathetic medical report.
You must write the core explanations, analysis, and text strictly in Roman Urdu (Urdu written in Latin/English script), while keeping the technical medical terms accurate.
"""

def get_report_prompt(json_output):
    return f"""
    Please analyze the following raw AI diagnostic results from RetiNexus Engine and generate a formal Medical Diagnostic Report strictly in Roman Urdu:
    
    {json_output}
    
    --- REQUIREMENTS & STRUCTURE ---
    Generate the entire report content using these exact headings (Keep headings in English formatting, but write all bullet points and descriptions inside them in clear Roman Urdu):
    
    ## 1. Executive Diagnostic Summary
    - Final predicted Diabetic Retinopathy (DR) grade aur exact consensus confidence score ko Roman Urdu mein interpret karein.
    - Kis deep learning backbone model (ResNet50/EfficientNet/DenseNet) ko winner state mili, wazahat karein.
    
    ## 2. Vascular Morphology & Biomarkers
    - Vessel morphology features (Vessel Tortuosity Index, Vessel Density Percentage, aur Branching Points Count) ka Roman Urdu mein khulasa likhein.
    - In values ka microvascular stability par kya asar hai, aasan Roman Urdu mein batayein.
    
    ## 3. Detected Lesions Profiling
    - Microaneurysms, hemorrhages, hard exudates, aur soft exudates ki tadaad (counts) ko Roman Urdu text ke sath list karein (e.g., "Koi microaneurysms detect nahi huay (0)").
    
    ## 4. Multi-Organ Systemic Risk Stratification
    - Cardiovascular Risk Index, Chronic Kidney Disease (CKD) Risk Index, aur Cerebrovascular Risk Index ko Roman Urdu mein clinical warning format mein translate karein.
    - Ocular-renal-cardiac linkage ko aasan Roman Urdu mein samjhayein ke aankh ki barik ragein dil, gurde aur dimagh ka aaina kaise hain.
    
    ## 5. Clinical Recommendations & Next Steps
    - Patient ke liye lifestyle modifications, routine monitoring protocols, ya specialist (ophthalmologist/cardiologist) referral ke actionable mashware Roman Urdu mein likhein.
    
    ---
    *Standardized Clinical Disclaimer: This report is generated by the RetiNexus clinical AI framework for informational and screening support only. It does not constitute a definitive medical diagnosis. All findings must be clinically correlated and validated through a comprehensive eye examination by a qualified ophthalmologist or vitreoretinal specialist before initiating any therapeutic interventions.*
    """


PATIENT_INTERPRETATION_SYSTEM_PROMPT = """
You are an experienced ophthalmologist writing the clinical interpretation section of a retinal
screening report. You write the way a specialist explains findings to a patient and their referring
physician: precise, evidence-led, and grounded strictly in the data provided — never speculating
beyond it. You always respond with strict, valid JSON only — no markdown, no code fences, no
commentary outside the JSON object.
"""

def get_patient_interpretation_prompt(json_output):
    return f"""
    Based on the following AI diagnostic results, write the clinical interpretation an ophthalmologist
    would give when discussing this report — clear enough for the patient to follow, precise enough
    for the referring physician.

    {json_output}

    Respond with ONLY a valid JSON object (no markdown, no code fences, no extra text) in exactly
    this shape:
    {{
      "summary": "Exactly ONE paragraph (no line breaks) that reads as the ophthalmologist's own interpretation of the retinal findings — the diabetic retinopathy grade and what it means for the eye — and how that same vascular picture relates to the heart, kidney, and cerebrovascular risk signals in this report. Close by noting that a qualified doctor must review and confirm this report.",
      "heart": "One or two sentences on the cardiovascular risk finding specifically, in the same clinical voice.",
      "kidney": "One or two sentences on the kidney (CKD) risk finding specifically, in the same clinical voice.",
      "brain": "One or two sentences on the cerebrovascular (stroke) risk finding specifically, in the same clinical voice."
    }}

    Rules:
    - "summary" must be exactly one paragraph. Each organ field must be one or two short sentences — no more.
    - Be direct and clinically grounded, not casual — but never alarmist, and never use unexplained jargon.
    - Do not include headings, labels, disclaimers, or markdown inside any JSON value.
    - Output only the raw JSON object — nothing before or after it.
    """