# src/llm_report/prompt_templates.py

CLINICAL_SYSTEM_PROMPT = """
You are an expert retinal specialist and clinical AI assistant. Your task is to interpret multi-modal deep learning diagnostics and convert raw JSON data into a highly professional, structured, and empathetic medical report.
You must write the core explanations, analysis, and text strictly in Roman Urdu (Urdu written in Latin/English script), while keeping the technical medical terms accurate.
"""

def get_report_prompt(json_output):
    return f"""
    Please analyze the following raw AI diagnostic results from RetiNexus Engine and generate a formal Medical Diagnostic Report strictly in Roman Urdu:
    
    {json_output}
    
    --- REQUIREMENTS & STRUCTURE ---
    Generate the entire report content using these exact headings (Keep headings in English formatting, but write all bullet points and descriptions inside them in clear Roman Urdu):
    
    ## 1. Executive Diagnostic Summary
    - Final predicted Diabetic Retinopathy (DR) grade aur exact consensus confidence score ko Roman Urdu mein interpret karein.
    - Kis deep learning backbone model (ResNet50/EfficientNet/DenseNet) ko winner state mili, wazahat karein.
    
    ## 2. Vascular Morphology & Biomarkers
    - Vessel morphology features (Vessel Tortuosity Index, Vessel Density Percentage, aur Branching Points Count) ka Roman Urdu mein khulasa likhein.
    - In values ka microvascular stability par kya asar hai, aasan Roman Urdu mein batayein.
    
    ## 3. Detected Lesions Profiling
    - Microaneurysms, hemorrhages, hard exudates, aur soft exudates ki tadaad (counts) ko Roman Urdu text ke sath list karein (e.g., "Koi microaneurysms detect nahi huay (0)").
    
    ## 4. Multi-Organ Systemic Risk Stratification
    - Cardiovascular Risk Index, Chronic Kidney Disease (CKD) Risk Index, aur Cerebrovascular Risk Index ko Roman Urdu mein clinical warning format mein translate karein.
    - Ocular-renal-cardiac linkage ko aasan Roman Urdu mein samjhayein ke aankh ki barik ragein dil, gurde aur dimagh ka aaina kaise hain.
    
    ## 5. Clinical Recommendations & Next Steps
    - Patient ke liye lifestyle modifications, routine monitoring protocols, ya specialist (ophthalmologist/cardiologist) referral ke actionable mashware Roman Urdu mein likhein.
    
    ---
    *Standardized Clinical Disclaimer: This report is generated by the RetiNexus clinical AI framework for informational and screening support only. It does not constitute a definitive medical diagnosis. All findings must be clinically correlated and validated through a comprehensive eye examination by a qualified ophthalmologist or vitreoretinal specialist before initiating any therapeutic interventions.*
    """